# Generated by Django 4.0.6 on 2022-07-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Todo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='name',
        ),
    ]
